### ISSUE TITLE
Fix bool serialization/deserialization behavior

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#57]
I offer to change the bool wrapper like I did in my fork: https://github.com/Footmau/gokeepasslib/commit/207e9691dc2e4a44e5d7b6aaafd48c9c93516918

It is more native KeePass logic.

Current gokeepasslib implementation lead to error when you try to open database in original KeePass application on in some other client because of "null" value in a bool property.

If you like that I can prepare pull request.

**Comment by tobischo** [comment]
While it has been a few years since I implemented that specific part, I believe there actually were cases where `null` was an allowed value and had the implication of "undecided/default".
Enforcing it to always be `True` or `False` would then break those cases 🤔 

Were the cases that you observed for files that were originally created with gokeepasslib or were they for files created with other applications?

Before changing this, I'd have to do some more research as to how KeePass2 behaves for those cases right now - which is the reference implementation that I'd refer to, independent of whether some other application cannot deal with it. Then that would be a bug on the side of that particular application.

**Comment by Footmau** [comment]
I can not to say what was exact path of reproduction.

Mostly I work with databases created in original KeePass app, then test it in my KPass Android app, then trying to open it in original Windows KeePass and other Android/MacOS apps.

I think some app could write empty string (or "yes", "1", enabled") as bool value, and then gokeepasslib translate it to "null" and after that I was failed to open database in KeePass.

You can check original logic in KeePassLib/Utility/StrUtil.cs StringToBool().

Also I have to say that this assertions fails only in KeePass debug mode. But after that there is an error message about incorrect base64 symbol and database doesn't opens in release build too. After I fixed this bool serialization, the base64 error disappeared to. I didn't investigate how them are depending or if they are.

**Comment by tobischo** [comment]
There is also `BoolToStringEx`: https://github.com/dlech/KeePass2.x/blob/4b4b02f4591629151bb51802c8cab3a4c26b9e52/KeePassLib/Utility/StrUtil.cs#L1134
This specifically supports `null`.

In that case the solution would probably be to extend `UnmarshalXMLAttr` to also support converting those values correctly. Since `null` is an option, that would have to be specifically handled though.

**Comment by Footmau** [comment]
BoolToStringEx  is used only for `EnableAutoType` and `EnableSearching`.
So, maybe we need to make extra methods that will be used only for that properties.

**Comment by Footmau** [comment]
Regarding the base64 error I was wrong.
It is still present, so I'll continue to investigate that separately.

**Comment by tobischo** [comment]
> So, maybe we need to make extra methods that will be used only for that properties.

Agreed. `OptionalBoolWrapper` or `NullableBoolWrapper` come to mind as types.
In that case changing `BoolWrapper` to no longer support `null` would be ok.

**Comment by tobischo** [comment]
#58 merged and released as v3.0.3

Once you find the base64 error, we can look into that further in a separate issue

**Comment by Footmau** [comment]
Regarding base64 error I'm not sure it is on the library side.
It seem's I forgot to set formatted option to false when I save kdbx4 database expiry time but KeePass expects base64 time string.
